// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: Country.proto
// Protobuf Java Version: 4.31.1

package com.joasasso.minitoolbox.tools.data;

@com.google.protobuf.Generated
public final class CountryOuterClass {
  private CountryOuterClass() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 31,
      /* patch= */ 1,
      /* suffix= */ "",
      CountryOuterClass.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface CountryOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.joasasso.minitoolbox.tools.data.Country)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string name = 1;</code>
     * @return The name.
     */
    java.lang.String getName();
    /**
     * <code>string name = 1;</code>
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>string official = 2;</code>
     * @return The official.
     */
    java.lang.String getOfficial();
    /**
     * <code>string official = 2;</code>
     * @return The bytes for official.
     */
    com.google.protobuf.ByteString
        getOfficialBytes();

    /**
     * <code>string native = 3;</code>
     * @return The native.
     */
    java.lang.String getNative();
    /**
     * <code>string native = 3;</code>
     * @return The bytes for native.
     */
    com.google.protobuf.ByteString
        getNativeBytes();

    /**
     * <code>string currency = 4;</code>
     * @return The currency.
     */
    java.lang.String getCurrency();
    /**
     * <code>string currency = 4;</code>
     * @return The bytes for currency.
     */
    com.google.protobuf.ByteString
        getCurrencyBytes();

    /**
     * <code>repeated string capital = 5;</code>
     * @return A list containing the capital.
     */
    java.util.List<java.lang.String>
        getCapitalList();
    /**
     * <code>repeated string capital = 5;</code>
     * @return The count of capital.
     */
    int getCapitalCount();
    /**
     * <code>repeated string capital = 5;</code>
     * @param index The index of the element to return.
     * @return The capital at the given index.
     */
    java.lang.String getCapital(int index);
    /**
     * <code>repeated string capital = 5;</code>
     * @param index The index of the value to return.
     * @return The bytes of the capital at the given index.
     */
    com.google.protobuf.ByteString
        getCapitalBytes(int index);

    /**
     * <code>string phoneCode = 6;</code>
     * @return The phoneCode.
     */
    java.lang.String getPhoneCode();
    /**
     * <code>string phoneCode = 6;</code>
     * @return The bytes for phoneCode.
     */
    com.google.protobuf.ByteString
        getPhoneCodeBytes();

    /**
     * <code>string flag = 7;</code>
     * @return The flag.
     */
    java.lang.String getFlag();
    /**
     * <code>string flag = 7;</code>
     * @return The bytes for flag.
     */
    com.google.protobuf.ByteString
        getFlagBytes();

    /**
     * <code>int64 population = 8;</code>
     * @return The population.
     */
    long getPopulation();
  }
  /**
   * Protobuf type {@code com.joasasso.minitoolbox.tools.data.Country}
   */
  public static final class Country extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.joasasso.minitoolbox.tools.data.Country)
      CountryOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 31,
        /* patch= */ 1,
        /* suffix= */ "",
        Country.class.getName());
    }
    // Use Country.newBuilder() to construct.
    private Country(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private Country() {
      name_ = "";
      official_ = "";
      native_ = "";
      currency_ = "";
      capital_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
      phoneCode_ = "";
      flag_ = "";
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.joasasso.minitoolbox.tools.data.CountryOuterClass.internal_static_com_joasasso_minitoolbox_tools_data_Country_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.joasasso.minitoolbox.tools.data.CountryOuterClass.internal_static_com_joasasso_minitoolbox_tools_data_Country_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.joasasso.minitoolbox.tools.data.CountryOuterClass.Country.class, com.joasasso.minitoolbox.tools.data.CountryOuterClass.Country.Builder.class);
    }

    public static final int NAME_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object name_ = "";
    /**
     * <code>string name = 1;</code>
     * @return The name.
     */
    @java.lang.Override
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 1;</code>
     * @return The bytes for name.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int OFFICIAL_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object official_ = "";
    /**
     * <code>string official = 2;</code>
     * @return The official.
     */
    @java.lang.Override
    public java.lang.String getOfficial() {
      java.lang.Object ref = official_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        official_ = s;
        return s;
      }
    }
    /**
     * <code>string official = 2;</code>
     * @return The bytes for official.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getOfficialBytes() {
      java.lang.Object ref = official_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        official_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NATIVE_FIELD_NUMBER = 3;
    @SuppressWarnings("serial")
    private volatile java.lang.Object native_ = "";
    /**
     * <code>string native = 3;</code>
     * @return The native.
     */
    @java.lang.Override
    public java.lang.String getNative() {
      java.lang.Object ref = native_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        native_ = s;
        return s;
      }
    }
    /**
     * <code>string native = 3;</code>
     * @return The bytes for native.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNativeBytes() {
      java.lang.Object ref = native_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        native_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CURRENCY_FIELD_NUMBER = 4;
    @SuppressWarnings("serial")
    private volatile java.lang.Object currency_ = "";
    /**
     * <code>string currency = 4;</code>
     * @return The currency.
     */
    @java.lang.Override
    public java.lang.String getCurrency() {
      java.lang.Object ref = currency_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        currency_ = s;
        return s;
      }
    }
    /**
     * <code>string currency = 4;</code>
     * @return The bytes for currency.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getCurrencyBytes() {
      java.lang.Object ref = currency_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        currency_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CAPITAL_FIELD_NUMBER = 5;
    @SuppressWarnings("serial")
    private com.google.protobuf.LazyStringArrayList capital_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    /**
     * <code>repeated string capital = 5;</code>
     * @return A list containing the capital.
     */
    public com.google.protobuf.ProtocolStringList
        getCapitalList() {
      return capital_;
    }
    /**
     * <code>repeated string capital = 5;</code>
     * @return The count of capital.
     */
    public int getCapitalCount() {
      return capital_.size();
    }
    /**
     * <code>repeated string capital = 5;</code>
     * @param index The index of the element to return.
     * @return The capital at the given index.
     */
    public java.lang.String getCapital(int index) {
      return capital_.get(index);
    }
    /**
     * <code>repeated string capital = 5;</code>
     * @param index The index of the value to return.
     * @return The bytes of the capital at the given index.
     */
    public com.google.protobuf.ByteString
        getCapitalBytes(int index) {
      return capital_.getByteString(index);
    }

    public static final int PHONECODE_FIELD_NUMBER = 6;
    @SuppressWarnings("serial")
    private volatile java.lang.Object phoneCode_ = "";
    /**
     * <code>string phoneCode = 6;</code>
     * @return The phoneCode.
     */
    @java.lang.Override
    public java.lang.String getPhoneCode() {
      java.lang.Object ref = phoneCode_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        phoneCode_ = s;
        return s;
      }
    }
    /**
     * <code>string phoneCode = 6;</code>
     * @return The bytes for phoneCode.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getPhoneCodeBytes() {
      java.lang.Object ref = phoneCode_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        phoneCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int FLAG_FIELD_NUMBER = 7;
    @SuppressWarnings("serial")
    private volatile java.lang.Object flag_ = "";
    /**
     * <code>string flag = 7;</code>
     * @return The flag.
     */
    @java.lang.Override
    public java.lang.String getFlag() {
      java.lang.Object ref = flag_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        flag_ = s;
        return s;
      }
    }
    /**
     * <code>string flag = 7;</code>
     * @return The bytes for flag.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getFlagBytes() {
      java.lang.Object ref = flag_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        flag_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int POPULATION_FIELD_NUMBER = 8;
    private long population_ = 0L;
    /**
     * <code>int64 population = 8;</code>
     * @return The population.
     */
    @java.lang.Override
    public long getPopulation() {
      return population_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(name_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 1, name_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(official_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 2, official_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(native_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 3, native_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(currency_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 4, currency_);
      }
      for (int i = 0; i < capital_.size(); i++) {
        com.google.protobuf.GeneratedMessage.writeString(output, 5, capital_.getRaw(i));
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(phoneCode_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 6, phoneCode_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(flag_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 7, flag_);
      }
      if (population_ != 0L) {
        output.writeInt64(8, population_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(name_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(1, name_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(official_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(2, official_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(native_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(3, native_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(currency_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(4, currency_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < capital_.size(); i++) {
          dataSize += computeStringSizeNoTag(capital_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getCapitalList().size();
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(phoneCode_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(6, phoneCode_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(flag_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(7, flag_);
      }
      if (population_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(8, population_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.joasasso.minitoolbox.tools.data.CountryOuterClass.Country)) {
        return super.equals(obj);
      }
      com.joasasso.minitoolbox.tools.data.CountryOuterClass.Country other = (com.joasasso.minitoolbox.tools.data.CountryOuterClass.Country) obj;

      if (!getName()
          .equals(other.getName())) return false;
      if (!getOfficial()
          .equals(other.getOfficial())) return false;
      if (!getNative()
          .equals(other.getNative())) return false;
      if (!getCurrency()
          .equals(other.getCurrency())) return false;
      if (!getCapitalList()
          .equals(other.getCapitalList())) return false;
      if (!getPhoneCode()
          .equals(other.getPhoneCode())) return false;
      if (!getFlag()
          .equals(other.getFlag())) return false;
      if (getPopulation()
          != other.getPopulation()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + OFFICIAL_FIELD_NUMBER;
      hash = (53 * hash) + getOfficial().hashCode();
      hash = (37 * hash) + NATIVE_FIELD_NUMBER;
      hash = (53 * hash) + getNative().hashCode();
      hash = (37 * hash) + CURRENCY_FIELD_NUMBER;
      hash = (53 * hash) + getCurrency().hashCode();
      if (getCapitalCount() > 0) {
        hash = (37 * hash) + CAPITAL_FIELD_NUMBER;
        hash = (53 * hash) + getCapitalList().hashCode();
      }
      hash = (37 * hash) + PHONECODE_FIELD_NUMBER;
      hash = (53 * hash) + getPhoneCode().hashCode();
      hash = (37 * hash) + FLAG_FIELD_NUMBER;
      hash = (53 * hash) + getFlag().hashCode();
      hash = (37 * hash) + POPULATION_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getPopulation());
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.joasasso.minitoolbox.tools.data.CountryOuterClass.Country parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.joasasso.minitoolbox.tools.data.CountryOuterClass.Country parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.joasasso.minitoolbox.tools.data.CountryOuterClass.Country parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.joasasso.minitoolbox.tools.data.CountryOuterClass.Country parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.joasasso.minitoolbox.tools.data.CountryOuterClass.Country parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.joasasso.minitoolbox.tools.data.CountryOuterClass.Country parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.joasasso.minitoolbox.tools.data.CountryOuterClass.Country parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.joasasso.minitoolbox.tools.data.CountryOuterClass.Country parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.joasasso.minitoolbox.tools.data.CountryOuterClass.Country parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.joasasso.minitoolbox.tools.data.CountryOuterClass.Country parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.joasasso.minitoolbox.tools.data.CountryOuterClass.Country parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.joasasso.minitoolbox.tools.data.CountryOuterClass.Country parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.joasasso.minitoolbox.tools.data.CountryOuterClass.Country prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.joasasso.minitoolbox.tools.data.Country}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.joasasso.minitoolbox.tools.data.Country)
        com.joasasso.minitoolbox.tools.data.CountryOuterClass.CountryOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.joasasso.minitoolbox.tools.data.CountryOuterClass.internal_static_com_joasasso_minitoolbox_tools_data_Country_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.joasasso.minitoolbox.tools.data.CountryOuterClass.internal_static_com_joasasso_minitoolbox_tools_data_Country_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.joasasso.minitoolbox.tools.data.CountryOuterClass.Country.class, com.joasasso.minitoolbox.tools.data.CountryOuterClass.Country.Builder.class);
      }

      // Construct using com.joasasso.minitoolbox.tools.data.CountryOuterClass.Country.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        name_ = "";
        official_ = "";
        native_ = "";
        currency_ = "";
        capital_ =
            com.google.protobuf.LazyStringArrayList.emptyList();
        phoneCode_ = "";
        flag_ = "";
        population_ = 0L;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.joasasso.minitoolbox.tools.data.CountryOuterClass.internal_static_com_joasasso_minitoolbox_tools_data_Country_descriptor;
      }

      @java.lang.Override
      public com.joasasso.minitoolbox.tools.data.CountryOuterClass.Country getDefaultInstanceForType() {
        return com.joasasso.minitoolbox.tools.data.CountryOuterClass.Country.getDefaultInstance();
      }

      @java.lang.Override
      public com.joasasso.minitoolbox.tools.data.CountryOuterClass.Country build() {
        com.joasasso.minitoolbox.tools.data.CountryOuterClass.Country result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.joasasso.minitoolbox.tools.data.CountryOuterClass.Country buildPartial() {
        com.joasasso.minitoolbox.tools.data.CountryOuterClass.Country result = new com.joasasso.minitoolbox.tools.data.CountryOuterClass.Country(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.joasasso.minitoolbox.tools.data.CountryOuterClass.Country result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.name_ = name_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.official_ = official_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.native_ = native_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.currency_ = currency_;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          capital_.makeImmutable();
          result.capital_ = capital_;
        }
        if (((from_bitField0_ & 0x00000020) != 0)) {
          result.phoneCode_ = phoneCode_;
        }
        if (((from_bitField0_ & 0x00000040) != 0)) {
          result.flag_ = flag_;
        }
        if (((from_bitField0_ & 0x00000080) != 0)) {
          result.population_ = population_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.joasasso.minitoolbox.tools.data.CountryOuterClass.Country) {
          return mergeFrom((com.joasasso.minitoolbox.tools.data.CountryOuterClass.Country)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.joasasso.minitoolbox.tools.data.CountryOuterClass.Country other) {
        if (other == com.joasasso.minitoolbox.tools.data.CountryOuterClass.Country.getDefaultInstance()) return this;
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (!other.getOfficial().isEmpty()) {
          official_ = other.official_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        if (!other.getNative().isEmpty()) {
          native_ = other.native_;
          bitField0_ |= 0x00000004;
          onChanged();
        }
        if (!other.getCurrency().isEmpty()) {
          currency_ = other.currency_;
          bitField0_ |= 0x00000008;
          onChanged();
        }
        if (!other.capital_.isEmpty()) {
          if (capital_.isEmpty()) {
            capital_ = other.capital_;
            bitField0_ |= 0x00000010;
          } else {
            ensureCapitalIsMutable();
            capital_.addAll(other.capital_);
          }
          onChanged();
        }
        if (!other.getPhoneCode().isEmpty()) {
          phoneCode_ = other.phoneCode_;
          bitField0_ |= 0x00000020;
          onChanged();
        }
        if (!other.getFlag().isEmpty()) {
          flag_ = other.flag_;
          bitField0_ |= 0x00000040;
          onChanged();
        }
        if (other.getPopulation() != 0L) {
          setPopulation(other.getPopulation());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                name_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                official_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 26: {
                native_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              case 34: {
                currency_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000008;
                break;
              } // case 34
              case 42: {
                java.lang.String s = input.readStringRequireUtf8();
                ensureCapitalIsMutable();
                capital_.add(s);
                break;
              } // case 42
              case 50: {
                phoneCode_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000020;
                break;
              } // case 50
              case 58: {
                flag_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000040;
                break;
              } // case 58
              case 64: {
                population_ = input.readInt64();
                bitField0_ |= 0x00000080;
                break;
              } // case 64
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object name_ = "";
      /**
       * <code>string name = 1;</code>
       * @return The name.
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 1;</code>
       * @return The bytes for name.
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 1;</code>
       * @param value The name to set.
       * @return This builder for chaining.
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        name_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearName() {
        name_ = getDefaultInstance().getName();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string name = 1;</code>
       * @param value The bytes for name to set.
       * @return This builder for chaining.
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        name_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private java.lang.Object official_ = "";
      /**
       * <code>string official = 2;</code>
       * @return The official.
       */
      public java.lang.String getOfficial() {
        java.lang.Object ref = official_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          official_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string official = 2;</code>
       * @return The bytes for official.
       */
      public com.google.protobuf.ByteString
          getOfficialBytes() {
        java.lang.Object ref = official_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          official_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string official = 2;</code>
       * @param value The official to set.
       * @return This builder for chaining.
       */
      public Builder setOfficial(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        official_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>string official = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearOfficial() {
        official_ = getDefaultInstance().getOfficial();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>string official = 2;</code>
       * @param value The bytes for official to set.
       * @return This builder for chaining.
       */
      public Builder setOfficialBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        official_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private java.lang.Object native_ = "";
      /**
       * <code>string native = 3;</code>
       * @return The native.
       */
      public java.lang.String getNative() {
        java.lang.Object ref = native_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          native_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string native = 3;</code>
       * @return The bytes for native.
       */
      public com.google.protobuf.ByteString
          getNativeBytes() {
        java.lang.Object ref = native_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          native_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string native = 3;</code>
       * @param value The native to set.
       * @return This builder for chaining.
       */
      public Builder setNative(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        native_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>string native = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearNative() {
        native_ = getDefaultInstance().getNative();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <code>string native = 3;</code>
       * @param value The bytes for native to set.
       * @return This builder for chaining.
       */
      public Builder setNativeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        native_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }

      private java.lang.Object currency_ = "";
      /**
       * <code>string currency = 4;</code>
       * @return The currency.
       */
      public java.lang.String getCurrency() {
        java.lang.Object ref = currency_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          currency_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string currency = 4;</code>
       * @return The bytes for currency.
       */
      public com.google.protobuf.ByteString
          getCurrencyBytes() {
        java.lang.Object ref = currency_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          currency_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string currency = 4;</code>
       * @param value The currency to set.
       * @return This builder for chaining.
       */
      public Builder setCurrency(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        currency_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>string currency = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearCurrency() {
        currency_ = getDefaultInstance().getCurrency();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }
      /**
       * <code>string currency = 4;</code>
       * @param value The bytes for currency to set.
       * @return This builder for chaining.
       */
      public Builder setCurrencyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        currency_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringArrayList capital_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
      private void ensureCapitalIsMutable() {
        if (!capital_.isModifiable()) {
          capital_ = new com.google.protobuf.LazyStringArrayList(capital_);
        }
        bitField0_ |= 0x00000010;
      }
      /**
       * <code>repeated string capital = 5;</code>
       * @return A list containing the capital.
       */
      public com.google.protobuf.ProtocolStringList
          getCapitalList() {
        capital_.makeImmutable();
        return capital_;
      }
      /**
       * <code>repeated string capital = 5;</code>
       * @return The count of capital.
       */
      public int getCapitalCount() {
        return capital_.size();
      }
      /**
       * <code>repeated string capital = 5;</code>
       * @param index The index of the element to return.
       * @return The capital at the given index.
       */
      public java.lang.String getCapital(int index) {
        return capital_.get(index);
      }
      /**
       * <code>repeated string capital = 5;</code>
       * @param index The index of the value to return.
       * @return The bytes of the capital at the given index.
       */
      public com.google.protobuf.ByteString
          getCapitalBytes(int index) {
        return capital_.getByteString(index);
      }
      /**
       * <code>repeated string capital = 5;</code>
       * @param index The index to set the value at.
       * @param value The capital to set.
       * @return This builder for chaining.
       */
      public Builder setCapital(
          int index, java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        ensureCapitalIsMutable();
        capital_.set(index, value);
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>repeated string capital = 5;</code>
       * @param value The capital to add.
       * @return This builder for chaining.
       */
      public Builder addCapital(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        ensureCapitalIsMutable();
        capital_.add(value);
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>repeated string capital = 5;</code>
       * @param values The capital to add.
       * @return This builder for chaining.
       */
      public Builder addAllCapital(
          java.lang.Iterable<java.lang.String> values) {
        ensureCapitalIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, capital_);
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>repeated string capital = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearCapital() {
        capital_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
        bitField0_ = (bitField0_ & ~0x00000010);;
        onChanged();
        return this;
      }
      /**
       * <code>repeated string capital = 5;</code>
       * @param value The bytes of the capital to add.
       * @return This builder for chaining.
       */
      public Builder addCapitalBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        ensureCapitalIsMutable();
        capital_.add(value);
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }

      private java.lang.Object phoneCode_ = "";
      /**
       * <code>string phoneCode = 6;</code>
       * @return The phoneCode.
       */
      public java.lang.String getPhoneCode() {
        java.lang.Object ref = phoneCode_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          phoneCode_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string phoneCode = 6;</code>
       * @return The bytes for phoneCode.
       */
      public com.google.protobuf.ByteString
          getPhoneCodeBytes() {
        java.lang.Object ref = phoneCode_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          phoneCode_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string phoneCode = 6;</code>
       * @param value The phoneCode to set.
       * @return This builder for chaining.
       */
      public Builder setPhoneCode(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        phoneCode_ = value;
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }
      /**
       * <code>string phoneCode = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearPhoneCode() {
        phoneCode_ = getDefaultInstance().getPhoneCode();
        bitField0_ = (bitField0_ & ~0x00000020);
        onChanged();
        return this;
      }
      /**
       * <code>string phoneCode = 6;</code>
       * @param value The bytes for phoneCode to set.
       * @return This builder for chaining.
       */
      public Builder setPhoneCodeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        phoneCode_ = value;
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }

      private java.lang.Object flag_ = "";
      /**
       * <code>string flag = 7;</code>
       * @return The flag.
       */
      public java.lang.String getFlag() {
        java.lang.Object ref = flag_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          flag_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string flag = 7;</code>
       * @return The bytes for flag.
       */
      public com.google.protobuf.ByteString
          getFlagBytes() {
        java.lang.Object ref = flag_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          flag_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string flag = 7;</code>
       * @param value The flag to set.
       * @return This builder for chaining.
       */
      public Builder setFlag(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        flag_ = value;
        bitField0_ |= 0x00000040;
        onChanged();
        return this;
      }
      /**
       * <code>string flag = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearFlag() {
        flag_ = getDefaultInstance().getFlag();
        bitField0_ = (bitField0_ & ~0x00000040);
        onChanged();
        return this;
      }
      /**
       * <code>string flag = 7;</code>
       * @param value The bytes for flag to set.
       * @return This builder for chaining.
       */
      public Builder setFlagBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        flag_ = value;
        bitField0_ |= 0x00000040;
        onChanged();
        return this;
      }

      private long population_ ;
      /**
       * <code>int64 population = 8;</code>
       * @return The population.
       */
      @java.lang.Override
      public long getPopulation() {
        return population_;
      }
      /**
       * <code>int64 population = 8;</code>
       * @param value The population to set.
       * @return This builder for chaining.
       */
      public Builder setPopulation(long value) {

        population_ = value;
        bitField0_ |= 0x00000080;
        onChanged();
        return this;
      }
      /**
       * <code>int64 population = 8;</code>
       * @return This builder for chaining.
       */
      public Builder clearPopulation() {
        bitField0_ = (bitField0_ & ~0x00000080);
        population_ = 0L;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.joasasso.minitoolbox.tools.data.Country)
    }

    // @@protoc_insertion_point(class_scope:com.joasasso.minitoolbox.tools.data.Country)
    private static final com.joasasso.minitoolbox.tools.data.CountryOuterClass.Country DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.joasasso.minitoolbox.tools.data.CountryOuterClass.Country();
    }

    public static com.joasasso.minitoolbox.tools.data.CountryOuterClass.Country getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Country>
        PARSER = new com.google.protobuf.AbstractParser<Country>() {
      @java.lang.Override
      public Country parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Country> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Country> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.joasasso.minitoolbox.tools.data.CountryOuterClass.Country getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface CountryListOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.joasasso.minitoolbox.tools.data.CountryList)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .com.joasasso.minitoolbox.tools.data.Country countries = 1;</code>
     */
    java.util.List<com.joasasso.minitoolbox.tools.data.CountryOuterClass.Country> 
        getCountriesList();
    /**
     * <code>repeated .com.joasasso.minitoolbox.tools.data.Country countries = 1;</code>
     */
    com.joasasso.minitoolbox.tools.data.CountryOuterClass.Country getCountries(int index);
    /**
     * <code>repeated .com.joasasso.minitoolbox.tools.data.Country countries = 1;</code>
     */
    int getCountriesCount();
    /**
     * <code>repeated .com.joasasso.minitoolbox.tools.data.Country countries = 1;</code>
     */
    java.util.List<? extends com.joasasso.minitoolbox.tools.data.CountryOuterClass.CountryOrBuilder> 
        getCountriesOrBuilderList();
    /**
     * <code>repeated .com.joasasso.minitoolbox.tools.data.Country countries = 1;</code>
     */
    com.joasasso.minitoolbox.tools.data.CountryOuterClass.CountryOrBuilder getCountriesOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code com.joasasso.minitoolbox.tools.data.CountryList}
   */
  public static final class CountryList extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.joasasso.minitoolbox.tools.data.CountryList)
      CountryListOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 31,
        /* patch= */ 1,
        /* suffix= */ "",
        CountryList.class.getName());
    }
    // Use CountryList.newBuilder() to construct.
    private CountryList(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private CountryList() {
      countries_ = java.util.Collections.emptyList();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.joasasso.minitoolbox.tools.data.CountryOuterClass.internal_static_com_joasasso_minitoolbox_tools_data_CountryList_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.joasasso.minitoolbox.tools.data.CountryOuterClass.internal_static_com_joasasso_minitoolbox_tools_data_CountryList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.joasasso.minitoolbox.tools.data.CountryOuterClass.CountryList.class, com.joasasso.minitoolbox.tools.data.CountryOuterClass.CountryList.Builder.class);
    }

    public static final int COUNTRIES_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private java.util.List<com.joasasso.minitoolbox.tools.data.CountryOuterClass.Country> countries_;
    /**
     * <code>repeated .com.joasasso.minitoolbox.tools.data.Country countries = 1;</code>
     */
    @java.lang.Override
    public java.util.List<com.joasasso.minitoolbox.tools.data.CountryOuterClass.Country> getCountriesList() {
      return countries_;
    }
    /**
     * <code>repeated .com.joasasso.minitoolbox.tools.data.Country countries = 1;</code>
     */
    @java.lang.Override
    public java.util.List<? extends com.joasasso.minitoolbox.tools.data.CountryOuterClass.CountryOrBuilder> 
        getCountriesOrBuilderList() {
      return countries_;
    }
    /**
     * <code>repeated .com.joasasso.minitoolbox.tools.data.Country countries = 1;</code>
     */
    @java.lang.Override
    public int getCountriesCount() {
      return countries_.size();
    }
    /**
     * <code>repeated .com.joasasso.minitoolbox.tools.data.Country countries = 1;</code>
     */
    @java.lang.Override
    public com.joasasso.minitoolbox.tools.data.CountryOuterClass.Country getCountries(int index) {
      return countries_.get(index);
    }
    /**
     * <code>repeated .com.joasasso.minitoolbox.tools.data.Country countries = 1;</code>
     */
    @java.lang.Override
    public com.joasasso.minitoolbox.tools.data.CountryOuterClass.CountryOrBuilder getCountriesOrBuilder(
        int index) {
      return countries_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < countries_.size(); i++) {
        output.writeMessage(1, countries_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < countries_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, countries_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.joasasso.minitoolbox.tools.data.CountryOuterClass.CountryList)) {
        return super.equals(obj);
      }
      com.joasasso.minitoolbox.tools.data.CountryOuterClass.CountryList other = (com.joasasso.minitoolbox.tools.data.CountryOuterClass.CountryList) obj;

      if (!getCountriesList()
          .equals(other.getCountriesList())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getCountriesCount() > 0) {
        hash = (37 * hash) + COUNTRIES_FIELD_NUMBER;
        hash = (53 * hash) + getCountriesList().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.joasasso.minitoolbox.tools.data.CountryOuterClass.CountryList parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.joasasso.minitoolbox.tools.data.CountryOuterClass.CountryList parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.joasasso.minitoolbox.tools.data.CountryOuterClass.CountryList parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.joasasso.minitoolbox.tools.data.CountryOuterClass.CountryList parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.joasasso.minitoolbox.tools.data.CountryOuterClass.CountryList parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.joasasso.minitoolbox.tools.data.CountryOuterClass.CountryList parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.joasasso.minitoolbox.tools.data.CountryOuterClass.CountryList parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.joasasso.minitoolbox.tools.data.CountryOuterClass.CountryList parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.joasasso.minitoolbox.tools.data.CountryOuterClass.CountryList parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.joasasso.minitoolbox.tools.data.CountryOuterClass.CountryList parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.joasasso.minitoolbox.tools.data.CountryOuterClass.CountryList parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.joasasso.minitoolbox.tools.data.CountryOuterClass.CountryList parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.joasasso.minitoolbox.tools.data.CountryOuterClass.CountryList prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.joasasso.minitoolbox.tools.data.CountryList}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.joasasso.minitoolbox.tools.data.CountryList)
        com.joasasso.minitoolbox.tools.data.CountryOuterClass.CountryListOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.joasasso.minitoolbox.tools.data.CountryOuterClass.internal_static_com_joasasso_minitoolbox_tools_data_CountryList_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.joasasso.minitoolbox.tools.data.CountryOuterClass.internal_static_com_joasasso_minitoolbox_tools_data_CountryList_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.joasasso.minitoolbox.tools.data.CountryOuterClass.CountryList.class, com.joasasso.minitoolbox.tools.data.CountryOuterClass.CountryList.Builder.class);
      }

      // Construct using com.joasasso.minitoolbox.tools.data.CountryOuterClass.CountryList.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        if (countriesBuilder_ == null) {
          countries_ = java.util.Collections.emptyList();
        } else {
          countries_ = null;
          countriesBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.joasasso.minitoolbox.tools.data.CountryOuterClass.internal_static_com_joasasso_minitoolbox_tools_data_CountryList_descriptor;
      }

      @java.lang.Override
      public com.joasasso.minitoolbox.tools.data.CountryOuterClass.CountryList getDefaultInstanceForType() {
        return com.joasasso.minitoolbox.tools.data.CountryOuterClass.CountryList.getDefaultInstance();
      }

      @java.lang.Override
      public com.joasasso.minitoolbox.tools.data.CountryOuterClass.CountryList build() {
        com.joasasso.minitoolbox.tools.data.CountryOuterClass.CountryList result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.joasasso.minitoolbox.tools.data.CountryOuterClass.CountryList buildPartial() {
        com.joasasso.minitoolbox.tools.data.CountryOuterClass.CountryList result = new com.joasasso.minitoolbox.tools.data.CountryOuterClass.CountryList(this);
        buildPartialRepeatedFields(result);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartialRepeatedFields(com.joasasso.minitoolbox.tools.data.CountryOuterClass.CountryList result) {
        if (countriesBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            countries_ = java.util.Collections.unmodifiableList(countries_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.countries_ = countries_;
        } else {
          result.countries_ = countriesBuilder_.build();
        }
      }

      private void buildPartial0(com.joasasso.minitoolbox.tools.data.CountryOuterClass.CountryList result) {
        int from_bitField0_ = bitField0_;
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.joasasso.minitoolbox.tools.data.CountryOuterClass.CountryList) {
          return mergeFrom((com.joasasso.minitoolbox.tools.data.CountryOuterClass.CountryList)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.joasasso.minitoolbox.tools.data.CountryOuterClass.CountryList other) {
        if (other == com.joasasso.minitoolbox.tools.data.CountryOuterClass.CountryList.getDefaultInstance()) return this;
        if (countriesBuilder_ == null) {
          if (!other.countries_.isEmpty()) {
            if (countries_.isEmpty()) {
              countries_ = other.countries_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureCountriesIsMutable();
              countries_.addAll(other.countries_);
            }
            onChanged();
          }
        } else {
          if (!other.countries_.isEmpty()) {
            if (countriesBuilder_.isEmpty()) {
              countriesBuilder_.dispose();
              countriesBuilder_ = null;
              countries_ = other.countries_;
              bitField0_ = (bitField0_ & ~0x00000001);
              countriesBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   internalGetCountriesFieldBuilder() : null;
            } else {
              countriesBuilder_.addAllMessages(other.countries_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                com.joasasso.minitoolbox.tools.data.CountryOuterClass.Country m =
                    input.readMessage(
                        com.joasasso.minitoolbox.tools.data.CountryOuterClass.Country.parser(),
                        extensionRegistry);
                if (countriesBuilder_ == null) {
                  ensureCountriesIsMutable();
                  countries_.add(m);
                } else {
                  countriesBuilder_.addMessage(m);
                }
                break;
              } // case 10
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.util.List<com.joasasso.minitoolbox.tools.data.CountryOuterClass.Country> countries_ =
        java.util.Collections.emptyList();
      private void ensureCountriesIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          countries_ = new java.util.ArrayList<com.joasasso.minitoolbox.tools.data.CountryOuterClass.Country>(countries_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          com.joasasso.minitoolbox.tools.data.CountryOuterClass.Country, com.joasasso.minitoolbox.tools.data.CountryOuterClass.Country.Builder, com.joasasso.minitoolbox.tools.data.CountryOuterClass.CountryOrBuilder> countriesBuilder_;

      /**
       * <code>repeated .com.joasasso.minitoolbox.tools.data.Country countries = 1;</code>
       */
      public java.util.List<com.joasasso.minitoolbox.tools.data.CountryOuterClass.Country> getCountriesList() {
        if (countriesBuilder_ == null) {
          return java.util.Collections.unmodifiableList(countries_);
        } else {
          return countriesBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .com.joasasso.minitoolbox.tools.data.Country countries = 1;</code>
       */
      public int getCountriesCount() {
        if (countriesBuilder_ == null) {
          return countries_.size();
        } else {
          return countriesBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .com.joasasso.minitoolbox.tools.data.Country countries = 1;</code>
       */
      public com.joasasso.minitoolbox.tools.data.CountryOuterClass.Country getCountries(int index) {
        if (countriesBuilder_ == null) {
          return countries_.get(index);
        } else {
          return countriesBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .com.joasasso.minitoolbox.tools.data.Country countries = 1;</code>
       */
      public Builder setCountries(
          int index, com.joasasso.minitoolbox.tools.data.CountryOuterClass.Country value) {
        if (countriesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureCountriesIsMutable();
          countries_.set(index, value);
          onChanged();
        } else {
          countriesBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.joasasso.minitoolbox.tools.data.Country countries = 1;</code>
       */
      public Builder setCountries(
          int index, com.joasasso.minitoolbox.tools.data.CountryOuterClass.Country.Builder builderForValue) {
        if (countriesBuilder_ == null) {
          ensureCountriesIsMutable();
          countries_.set(index, builderForValue.build());
          onChanged();
        } else {
          countriesBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.joasasso.minitoolbox.tools.data.Country countries = 1;</code>
       */
      public Builder addCountries(com.joasasso.minitoolbox.tools.data.CountryOuterClass.Country value) {
        if (countriesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureCountriesIsMutable();
          countries_.add(value);
          onChanged();
        } else {
          countriesBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .com.joasasso.minitoolbox.tools.data.Country countries = 1;</code>
       */
      public Builder addCountries(
          int index, com.joasasso.minitoolbox.tools.data.CountryOuterClass.Country value) {
        if (countriesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureCountriesIsMutable();
          countries_.add(index, value);
          onChanged();
        } else {
          countriesBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.joasasso.minitoolbox.tools.data.Country countries = 1;</code>
       */
      public Builder addCountries(
          com.joasasso.minitoolbox.tools.data.CountryOuterClass.Country.Builder builderForValue) {
        if (countriesBuilder_ == null) {
          ensureCountriesIsMutable();
          countries_.add(builderForValue.build());
          onChanged();
        } else {
          countriesBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.joasasso.minitoolbox.tools.data.Country countries = 1;</code>
       */
      public Builder addCountries(
          int index, com.joasasso.minitoolbox.tools.data.CountryOuterClass.Country.Builder builderForValue) {
        if (countriesBuilder_ == null) {
          ensureCountriesIsMutable();
          countries_.add(index, builderForValue.build());
          onChanged();
        } else {
          countriesBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.joasasso.minitoolbox.tools.data.Country countries = 1;</code>
       */
      public Builder addAllCountries(
          java.lang.Iterable<? extends com.joasasso.minitoolbox.tools.data.CountryOuterClass.Country> values) {
        if (countriesBuilder_ == null) {
          ensureCountriesIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, countries_);
          onChanged();
        } else {
          countriesBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .com.joasasso.minitoolbox.tools.data.Country countries = 1;</code>
       */
      public Builder clearCountries() {
        if (countriesBuilder_ == null) {
          countries_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          countriesBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .com.joasasso.minitoolbox.tools.data.Country countries = 1;</code>
       */
      public Builder removeCountries(int index) {
        if (countriesBuilder_ == null) {
          ensureCountriesIsMutable();
          countries_.remove(index);
          onChanged();
        } else {
          countriesBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .com.joasasso.minitoolbox.tools.data.Country countries = 1;</code>
       */
      public com.joasasso.minitoolbox.tools.data.CountryOuterClass.Country.Builder getCountriesBuilder(
          int index) {
        return internalGetCountriesFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .com.joasasso.minitoolbox.tools.data.Country countries = 1;</code>
       */
      public com.joasasso.minitoolbox.tools.data.CountryOuterClass.CountryOrBuilder getCountriesOrBuilder(
          int index) {
        if (countriesBuilder_ == null) {
          return countries_.get(index);  } else {
          return countriesBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .com.joasasso.minitoolbox.tools.data.Country countries = 1;</code>
       */
      public java.util.List<? extends com.joasasso.minitoolbox.tools.data.CountryOuterClass.CountryOrBuilder> 
           getCountriesOrBuilderList() {
        if (countriesBuilder_ != null) {
          return countriesBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(countries_);
        }
      }
      /**
       * <code>repeated .com.joasasso.minitoolbox.tools.data.Country countries = 1;</code>
       */
      public com.joasasso.minitoolbox.tools.data.CountryOuterClass.Country.Builder addCountriesBuilder() {
        return internalGetCountriesFieldBuilder().addBuilder(
            com.joasasso.minitoolbox.tools.data.CountryOuterClass.Country.getDefaultInstance());
      }
      /**
       * <code>repeated .com.joasasso.minitoolbox.tools.data.Country countries = 1;</code>
       */
      public com.joasasso.minitoolbox.tools.data.CountryOuterClass.Country.Builder addCountriesBuilder(
          int index) {
        return internalGetCountriesFieldBuilder().addBuilder(
            index, com.joasasso.minitoolbox.tools.data.CountryOuterClass.Country.getDefaultInstance());
      }
      /**
       * <code>repeated .com.joasasso.minitoolbox.tools.data.Country countries = 1;</code>
       */
      public java.util.List<com.joasasso.minitoolbox.tools.data.CountryOuterClass.Country.Builder> 
           getCountriesBuilderList() {
        return internalGetCountriesFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.joasasso.minitoolbox.tools.data.CountryOuterClass.Country, com.joasasso.minitoolbox.tools.data.CountryOuterClass.Country.Builder, com.joasasso.minitoolbox.tools.data.CountryOuterClass.CountryOrBuilder> 
          internalGetCountriesFieldBuilder() {
        if (countriesBuilder_ == null) {
          countriesBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.joasasso.minitoolbox.tools.data.CountryOuterClass.Country, com.joasasso.minitoolbox.tools.data.CountryOuterClass.Country.Builder, com.joasasso.minitoolbox.tools.data.CountryOuterClass.CountryOrBuilder>(
                  countries_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          countries_ = null;
        }
        return countriesBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:com.joasasso.minitoolbox.tools.data.CountryList)
    }

    // @@protoc_insertion_point(class_scope:com.joasasso.minitoolbox.tools.data.CountryList)
    private static final com.joasasso.minitoolbox.tools.data.CountryOuterClass.CountryList DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.joasasso.minitoolbox.tools.data.CountryOuterClass.CountryList();
    }

    public static com.joasasso.minitoolbox.tools.data.CountryOuterClass.CountryList getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CountryList>
        PARSER = new com.google.protobuf.AbstractParser<CountryList>() {
      @java.lang.Override
      public CountryList parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<CountryList> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CountryList> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.joasasso.minitoolbox.tools.data.CountryOuterClass.CountryList getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_joasasso_minitoolbox_tools_data_Country_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_joasasso_minitoolbox_tools_data_Country_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_joasasso_minitoolbox_tools_data_CountryList_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_joasasso_minitoolbox_tools_data_CountryList_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rCountry.proto\022#com.joasasso.minitoolbo" +
      "x.tools.data\"\221\001\n\007Country\022\014\n\004name\030\001 \001(\t\022\020" +
      "\n\010official\030\002 \001(\t\022\016\n\006native\030\003 \001(\t\022\020\n\010curr" +
      "ency\030\004 \001(\t\022\017\n\007capital\030\005 \003(\t\022\021\n\tphoneCode" +
      "\030\006 \001(\t\022\014\n\004flag\030\007 \001(\t\022\022\n\npopulation\030\010 \001(\003" +
      "\"N\n\013CountryList\022?\n\tcountries\030\001 \003(\0132,.com" +
      ".joasasso.minitoolbox.tools.data.Country" +
      "b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_joasasso_minitoolbox_tools_data_Country_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_joasasso_minitoolbox_tools_data_Country_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_joasasso_minitoolbox_tools_data_Country_descriptor,
        new java.lang.String[] { "Name", "Official", "Native", "Currency", "Capital", "PhoneCode", "Flag", "Population", });
    internal_static_com_joasasso_minitoolbox_tools_data_CountryList_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_joasasso_minitoolbox_tools_data_CountryList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_joasasso_minitoolbox_tools_data_CountryList_descriptor,
        new java.lang.String[] { "Countries", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
